# Generated by Django 4.0.6 on 2022-07-29 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiaries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('eligibility', models.TextField(verbose_name='Beneficiary eligibility')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('total_budget', models.DecimalField(decimal_places=4, max_digits=24)),
                ('budget_per_beneficiary', models.DecimalField(decimal_places=4, max_digits=24)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCoordinators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_date_time', models.DateTimeField(auto_now_add=True)),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projects')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectBeneficiaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_receive_date_time', models.DateTimeField(blank=True, null=True)),
                ('beneficiary_join_date_time', models.DateTimeField(auto_now_add=True)),
                ('benefactor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiaries.beneficiaries')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projects')),
            ],
        ),
        migrations.AddConstraint(
            model_name='projectcoordinators',
            constraint=models.UniqueConstraint(fields=('project', 'coordinator'), name='projects_projectcoordinators__check_project_and_coordinator_is_unique_together'),
        ),
        migrations.AddConstraint(
            model_name='projectbeneficiaries',
            constraint=models.UniqueConstraint(fields=('project', 'beneficiary'), name='projects_projectbeneficiaries__check_project_and_beneficiary_is_unique_together'),
        ),
    ]
