# Generated by Django 4.0.6 on 2022-07-29 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectbeneficiaries',
            options={'verbose_name': 'Project Beneficiary', 'verbose_name_plural': 'Project Beneficiaries'},
        ),
        migrations.AlterModelOptions(
            name='projectcoordinators',
            options={'verbose_name': 'Project Coordinator', 'verbose_name_plural': 'Project Coordinators'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
    ]
