# Generated by Django 4.0.6 on 2022-07-29 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostOffice',
            new_name='PostCode',
        ),
        migrations.AlterModelOptions(
            name='beneficiaries',
            options={'verbose_name': 'Beneficiary', 'verbose_name_plural': 'Beneficiaries'},
        ),
        migrations.AlterModelOptions(
            name='beneficiaryaddress',
            options={'verbose_name': 'Beneficiary Address', 'verbose_name_plural': 'Beneficiary Addresses'},
        ),
        migrations.RenameField(
            model_name='beneficiaryaddress',
            old_name='Village',
            new_name='village',
        ),
    ]
