# Generated by Django 4.0.6 on 2022-07-29 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0002_rename_postoffice_postcode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficiaryaddress',
            old_name='post_office',
            new_name='post_code',
        ),
    ]
