# Generated by Django 4.0.6 on 2022-07-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customusermodel_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Profile Picture'),
        ),
    ]
